### ISSUE TITLE
Formalization of rules 

### ISSUE THREAD

**Issue by tapaswenipathak** [alice-sieve/Linux-Kernel#88]
ref https://github.com/alice-sieve/Linux-Kernel/issues/80.

I will work w/ you on this and reviews.

**Comment by deyachatterjee** [comment]
I am not pursuing the work this month, so kindly donot tag me in issues.
Since you are the owner of the github org, feel free to remove me.

Regarding whether I would be free next month as you asked, I cannot
determine right now and will set up a call as per procedure if I am.

Kindly close the issue(s) related to me on Github.

Thanks for understanding.

Regards,
Deya
